import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import InstrumentContainer from "../components/InstrumentContainer";
import { useContext, useEffect, useState } from "react";
import MeasuresContainer from "../components/MeasuresContainer";
import {
  InstrumentsContext,
  InstrumentsContextProvider,
} from "../hooks/InstrumentContext";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPause, faPlay, faVolumeHigh, faVolumeMute } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  const [togglePlayer, setTogglePlayer] = useState(true);
  const [gesture, setGesture] = useState(false);
  const { start, stop, vol } = useContext(InstrumentsContext);
  const [volume, setVolume] = useState(1);
  const handleToggle = () => {
    if (togglePlayer) {
      start();
    } else {
      stop();
    }
    setTogglePlayer(!togglePlayer);
  }

  const handleVolumeChange = (e) => {

    setVolume(e.target.value);
    vol.current.volume.value = e.target.value;
    console.log(vol.current.volume)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="main_app_container">
          <MeasuresContainer />
          <div className="instruments">
            <div className="instrument-types-label">
              <div className="controls-container">
                <button
                style={{
                  height: '30px',
                  width: '30px',
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                  borderRadius: '100%'
                }}
                className="play-button"
                  onClick={handleToggle}>
                  {togglePlayer ? <FontAwesomeIcon height={30} icon={faPlay}/> : <FontAwesomeIcon height={30}icon={faPause}/>}
                </button>
                <div className="volume-container">
                  <FontAwesomeIcon height={20} icon={faVolumeMute} /> <input max={4} min={-80} onChange={handleVolumeChange} value={volume} type="range" id="volume-slider"></input> <FontAwesomeIcon height={20} icon={faVolumeHigh}/>
                </div>
              </div>
              <div>Instrument Types</div>
            </div>

            <div className="instruments-container">
              <InstrumentContainer
                name="kick"
                color="#455192"
                instrument_ident="kick"
              />
              <InstrumentContainer
                name="snare"
                color="#455192"
                instrument_ident="snare"
              />
              <InstrumentContainer
                name="cymbal"
                color="#455192"
                instrument_ident="cymbal"
              />
              <InstrumentContainer
                name="bass"
                color="#779F68"
                instrument_ident="bass"
              />
              <InstrumentContainer
                name="melody"
                color="#B95264"
                instrument_ident="melody"
              />
              <InstrumentContainer
                name="auxiliary"
                color="#D2C761"
                instrument_ident="auxiliary"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
